export const Endpoints = {
	// Auth
	AuthLogin: "/auth/login",
	AuthSignUp: "/auth/sign-up",
	AuthMe: "/auth/me",
	// Crews
	CrewsCreate: "/crews",
	CrewsList: "/crews",
	CrewsGetByCode: "/crews/:code",
	CrewsUpdate: "/crews/:id",
	CrewsUpdateConfig: "/crews/update-config/",
	CrewsDelete: "/crews/:id",
	CrewsJoin: "/crews/join",
	CrewsLeave: "/crews/leave",
	CrewsUpdateAdmins: "/crews/update-admins/",
	CrewsAcceptMember: "/crews/accept-member",
	CrewsKickMember: "/crews/kick-member",
	// Users
	UsersCreate: "/users",
	UsersList: "/users",
	UsersGet: "/users/:id",
	UsersUpdate: "/users/:id",
	UsersDelete: "/users/:id",
	UsersSendFriendRequest: "/users/friends/send-request",
	UsersAcceptFriendRequest: "/users/friends/accept-request",
	UsersRejectFriendRequest: "/users/friends/reject-request",
	UsersRemoveFriend: "/users/friends/remove",
	UsersCreateHealthy: "/users/healthy",
};
