export enum SystemErrors {
	
	// General
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	// Auth
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	// Crew
	CREW_NOT_FOUND = "CREW_NOT_FOUND",
	ALREADY_MEMBER = "ALREADY_MEMBER",
	ALREADY_IN_WHITELIST = "ALREADY_IN_WHITELIST",
	INVALID_DATE = "INVALID_DATE",
	// Workout
	INVALID_WORKOUT_DATE = "INVALID_WORKOUT_DATE",
	WORKOUT_DATE_IN_FUTURE = "WORKOUT_DATE_IN_FUTURE",
	WORKOUT_DATE_TOO_OLD = "WORKOUT_DATE_TOO_OLD",
	CREW_RULES_VIOLATION = "CREW_RULES_VIOLATION",
	WORKOUT_DATE_OLDER_THAN_CREW = "WORKOUT_DATE_OLDER_THAN_CREW",
	// User
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_NOT_A_MEMBER = "USER_NOT_A_MEMBER",
	USER_NOT_IN_WHITELIST = "USER_NOT_IN_WHITELIST",
	ALREADY_FRIENDS = "ALREADY_FRIENDS",
	// Journey
	JOURNEY_NOT_FOUND = "JOURNEY_NOT_FOUND",
}

export type TSystemErrors = keyof typeof SystemErrors;
