export enum SystemErrors {
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	// Crew
	CREW_NOT_FOUND = "CREW_NOT_FOUND",
	ALREADY_MEMBER = "ALREADY_MEMBER",
	ALREADY_IN_WHITELIST = "ALREADY_IN_WHITELIST",
	// User related
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_NOT_A_MEMBER = "USER_NOT_A_MEMBER",
	USER_NOT_IN_WHITELIST = "USER_NOT_IN_WHITELIST",
	ALREADY_FRIENDS = "ALREADY_FRIENDS",
	ALREADY_REQUESTED = "ALREADY_REQUESTED",
	REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
	JOURNEY_NOT_FOUND = "JOURNEY_NOT_FOUND",
	
}

export type TSystemErrors = keyof typeof SystemErrors;
